blank_issues_enabled: false
contact_links:
  - name: Issue Tracker
    url: https://github.com/opencollective/opencollective/issues
    about: Repository to track issues across all our projects
  - name: Discord Channel
    url: https://discord.opencollective.com
    about: Engage with the Open Collective community
  - name: Documentation
    url: https://docs.opencollective.com/help/
    about: Documentation for Open Collective
  - name: Security Policy
    url: https://github.com/opencollective/opencollective/security/policy
    about: Please report security vulnerabilities as outlined here
