version: '3'
services:
  api:
    build: ./api
    command: /usr/src/api/docker/wait-for-db.sh npm run dev
    environment:
      NODE_ENV: "docker"
      SEQUELIZE_ENV: "docker"
    volumes:
      - ..:/usr/src/api
    ports:
      - "13060:3060"
    depends_on:
      - postgres
  postgres:
    # Using this image referenced by the following github issue:
    # https://github.com/docker-library/postgres/issues/199
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_PASSWORD: ""
    ports:
      - "15432:5432"

  # Please make sure both your API and your frontend were cloned under
  # the same parent directory
  frontend:
    build: ./frontend
    environment:
      NODE_ENV: "docker"
      API_KEY: "dvl-1510egmf4a23d80342403fb599qd"
      WEBSITE_URL: "http://localhost:13000"
      API_URL: "http://api:3060"
    volumes:
      - ../../frontend:/usr/src/frontend
    ports:
      - "13000:3000"
    depends_on:
      - api
    command: 'sh -c "npm install ; npm run dev || (npm run build && npm run dev)"'
